name: plasmapy

channels:
  - astropy

dependencies:
  - python=3.6
  - numpy
  - scipy
  - astropy
  - pip:
    - numpydoc
    - pytest
    - coveralls
    - mpmath
    - matplotlib
    - sphinx
    - sphinx-gallery
    - sphinx-automodapi
    - pillow
